baseURL = "/"
locale = "zh-CN"
title = "hugo warmpaper theme"
theme = "warmpaper"

mainSections = ["posts"]

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    [markup.goldmark.extensions.alert]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    noClasses = false
    style = "friendly"
    tabWidth = 4
    lineNos = false
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 2
    ordered = false

[permalinks]
  page = "/:contentbasename/"

[paginate]
  pagerSize = 10

[params]
  [[params.menu]]
    name = "Home"
    url = "/"
  [[params.menu]]
    name = "Archives"
    url = "/archives"
  [[params.menu]]
    name = "Tags"
    url = "/tags"
  [[params.menu]]
    name = "Categories"
    url = "/categories"
  [[params.menu]]
    name = "About"
    url = "/about"

  [params.profile]
    avatar = "/images/logo.svg"
    description = "A warm place for thoughts and code."
    [[params.profile.links]]
      name = "GitHub"
      url = "https://github.com/finch-xu/"
      icon = "github"
    [[params.profile.links]]
      name = "Website"
      url = "https://pidan.dev"
      icon = "website"

  [params.toc]
    enable = true
    max_depth = 3
    min_depth = 2
    list_number = false

  excerpt_link = "Read More"
  copyright = ""
